name: 'Setup Node.js'
description: 'Setup pnpm and Node.js with caching from .node-version'

inputs:
  cache:
    description: 'Enable pnpm caching'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'
        cache: ${{ inputs.cache == 'true' && 'pnpm' || '' }}
