'use client';

import * as React from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import Box from '@mui/joy/Box';
import Stack from '@mui/joy/Stack';
import Button from '@mui/joy/Button';
import Input from '@mui/joy/Input';
import Textarea from '@mui/joy/Textarea';
import Select from '@mui/joy/Select';
import Option from '@mui/joy/Option';
import FormControl from '@mui/joy/FormControl';
import FormLabel from '@mui/joy/FormLabel';
import FormHelperText from '@mui/joy/FormHelperText';
import Alert from '@mui/joy/Alert';
import Modal from '@mui/joy/Modal';
import ModalDialog from '@mui/joy/ModalDialog';
import ModalClose from '@mui/joy/ModalClose';
import Typography from '@mui/joy/Typography';
import CircularProgress from '@mui/joy/CircularProgress';
import { MagicWand, FloppyDisk } from '@phosphor-icons/react/dist/ssr';
import { 
  useCreateStyleGuide, 
  useUpdateStyleGuide, 
  useStyleGuide,
  useDeleteStyleGuide 
} from '../../hooks/use-style-guides';
import { createClient } from '@/lib/supabase/client';
import { useQuery } from '@tanstack/react-query';
import {
  getFormalityOptionItems,
  getSentenceOptionItems,
  getPacingOptionItems,
  getHumorUsageOptionItems,
  getStorytellingOptionItems,
  getUseOfJargonOptionItems,
  getLanguageLevelOptionItems,
} from '../../api/option-items';
import type { StyleGuideResponse } from '../../api/style-guides';
import { createStyleGuidePayloadSchema } from '../../types/validation';
import type { z } from 'zod';
import { paths } from '@/paths';
import { toast } from '@/components/core/toaster';
import { getCustomerById } from '@/lib/api/customers';

type FormData = z.infer<typeof createStyleGuidePayloadSchema>;

interface StyleGuideEditorProps {
  styleGuideId?: string;
  initialData?: StyleGuideResponse;
  customerId: string;
}

export function StyleGuideEditor({ 
  styleGuideId, 
  initialData,
  customerId 
}: StyleGuideEditorProps): React.JSX.Element {
  const router = useRouter();
  const [showDiscardModal, setShowDiscardModal] = React.useState(false);
  const [showReanalyzeModal, setShowReanalyzeModal] = React.useState(false);
  const [isReanalyzing, setIsReanalyzing] = React.useState(false);
  const [websiteUrl, setWebsiteUrl] = React.useState<string>('');

  // Fetch existing style guide if editing
  const { data: existingGuide } = useStyleGuide(styleGuideId || null);

  const guide = existingGuide || initialData;

  // Fetch customer data for autopopulating guide name
  const { data: customer } = useQuery({
    queryKey: ['customer', customerId],
    queryFn: () => getCustomerById(customerId),
    enabled: !!customerId && !styleGuideId, // Only fetch when creating (not editing)
  });

  // Fetch option items
  const { data: formalityOptions = [] } = useQuery({
    queryKey: ['formality-options'],
    queryFn: getFormalityOptionItems,
  });
  const { data: sentenceOptions = [], isLoading: isLoadingSentenceOptions } = useQuery({
    queryKey: ['sentence-options'],
    queryFn: getSentenceOptionItems,
  });

  // Debug: Log sentence options
  React.useEffect(() => {
    if (sentenceOptions.length > 0) {
      console.log('Sentence options loaded:', sentenceOptions);
    }
  }, [sentenceOptions]);
  const { data: pacingOptions = [] } = useQuery({
    queryKey: ['pacing-options'],
    queryFn: getPacingOptionItems,
  });
  const { data: humorOptions = [] } = useQuery({
    queryKey: ['humor-options'],
    queryFn: getHumorUsageOptionItems,
  });
  const { data: storytellingOptions = [] } = useQuery({
    queryKey: ['storytelling-options'],
    queryFn: getStorytellingOptionItems,
  });
  const { data: jargonOptions = [] } = useQuery({
    queryKey: ['jargon-options'],
    queryFn: getUseOfJargonOptionItems,
  });
  const { data: languageOptions = [] } = useQuery({
    queryKey: ['language-options'],
    queryFn: getLanguageLevelOptionItems,
  });

  // Auto-generate guide name when creating new guide
  const autoGeneratedGuideName = React.useMemo(() => {
    if (styleGuideId || guide?.guide_name) {
      // Editing existing guide - use existing name
      return guide?.guide_name || '';
    }
    // Creating new guide - use customer name
    return customer?.name ? `${customer.name} - Style Guide` : '';
  }, [styleGuideId, guide?.guide_name, customer?.name]);

  const defaultValues: Partial<FormData> = {
    customer_id: customerId, // Include customer_id for validation
    guide_name: autoGeneratedGuideName,
    brand_personality: guide?.brand_personality || '',
    brand_voice: guide?.brand_voice || '',
    formality_option_item_id: guide?.formality_option_item_id || null,
    sentence_length_option_item_id: guide?.sentence_length_option_item_id || null,
    pacing_option_item_id: guide?.pacing_option_item_id || null,
    humor_usage_option_item_id: guide?.humor_usage_option_item_id || null,
    storytelling_style_option_item_id: guide?.storytelling_style_option_item_id || null,
    use_of_jargon_option_item_id: guide?.use_of_jargon_option_item_id || null,
    language_level_option_item_id: guide?.language_level_option_item_id || null,
    inclusivity_guidelines: guide?.inclusivity_guidelines || '',
    active: guide?.active ?? true,
  };


  const {
    register,
    handleSubmit,
    formState: { errors, isDirty, isSubmitting },
    setValue,
    watch,
    reset,
  } = useForm<FormData>({
    resolver: zodResolver(createStyleGuidePayloadSchema),
    defaultValues,
    mode: 'onChange',
  });

  // Update customer_id in form when it becomes available
  React.useEffect(() => {
    if (customerId) {
      setValue('customer_id', customerId);
    }
  }, [customerId, setValue]);

  // Update guide name when customer data loads (only for new guides)
  React.useEffect(() => {
    if (!styleGuideId && customer?.name && !guide?.guide_name) {
      const generatedName = `${customer.name} - Style Guide`;
      setValue('guide_name', generatedName);
    }
  }, [customer?.name, styleGuideId, guide?.guide_name, setValue]);

  const createMutation = useCreateStyleGuide();
  const updateMutation = useUpdateStyleGuide();
  const deleteMutation = useDeleteStyleGuide();

  // Fetch customer email_domain for URL pre-fill
  React.useEffect(() => {
    const fetchCustomerDomain = async () => {
      if (!customerId) return;

      try {
        const supabase = createClient();
        const { data, error } = await supabase
          .from('customers')
          .select('email_domain')
          .eq('customer_id', customerId)
          .single();

        if (error) {
          console.error('Error fetching customer:', error);
          return;
        }

        if (data?.email_domain) {
          const domain = data.email_domain;
          const httpsUrl = `https://www.${domain}`;
          setWebsiteUrl(httpsUrl);
        }
      } catch (err) {
        console.error('Exception fetching customer data:', err);
      }
    };

    fetchCustomerDomain();
  }, [customerId]);

  const handleReanalyzeSite = () => {
    setShowReanalyzeModal(true);
  };

  const handleConfirmReanalyze = async () => {
    const actualStyleGuideId = styleGuideId || guide?.style_guide_id;
    
    if (!actualStyleGuideId || !websiteUrl) {
      toast.error('Style guide ID or website URL not available');
      return;
    }

    setIsReanalyzing(true);
    setShowReanalyzeModal(false);

    try {
      // Delete the current style guide
      console.log('Deleting current style guide:', actualStyleGuideId);
      await deleteMutation.mutateAsync(actualStyleGuideId);
      
      // Call the edge function to regenerate
      console.log('Regenerating style guide for URL:', websiteUrl);
      const supabase = createClient();
      
      const { data, error } = await supabase.functions.invoke('create-initial-written-style-guide-for-customer-id', {
        body: { 
          customer_id: customerId,
          url: websiteUrl 
        },
      });

      if (error) {
        console.error('Error regenerating style guide:', error);
        toast.error(`Failed to regenerate style guide: ${error.message}`);
        setIsReanalyzing(false);
        return;
      }

      console.log('Style guide regenerated successfully:', data);
      toast.success('Style guide regenerated successfully! Reloading page...');
      
      // Reload the page to show the new style guide
      setTimeout(() => {
        window.location.reload();
      }, 1500);
    } catch (err) {
      console.error('Exception regenerating style guide:', err);
      toast.error('An unexpected error occurred while regenerating the style guide');
      setIsReanalyzing(false);
    }
  };

  const onSubmit = async (data: FormData) => {
    try {
      console.log('Form submitted with data:', data);
      console.log('Customer ID:', customerId);
      console.log('Style Guide ID (prop):', styleGuideId);
      console.log('Guide to edit ID:', guide?.style_guide_id);
      
      if (!customerId || !data.customer_id) {
        toast.error('Customer ID is required');
        return;
      }

      // Determine the actual style guide ID - use prop first, then guide data
      const actualStyleGuideId = styleGuideId || guide?.style_guide_id;

      const payload = {
        ...data,
        customer_id: data.customer_id || customerId,
      };

      console.log('Submitting payload:', payload);
      console.log('Actual Style Guide ID:', actualStyleGuideId);

      // Always update if we have a style guide ID
      if (actualStyleGuideId) {
        console.log('Updating existing style guide:', actualStyleGuideId);
        await updateMutation.mutateAsync({
          style_guide_id: actualStyleGuideId,
          ...payload,
        });
        toast.success('Style guide updated successfully');
      } else {
        // Only create if no style guide ID exists
        console.log('Creating new style guide');
        await createMutation.mutateAsync(payload);
        toast.success('Style guide created successfully');
      }
    } catch (error) {
      console.error('Error submitting style guide:', error);
      toast.error(error instanceof Error ? error.message : 'Failed to save style guide');
    }
  };

  const onError = (errors: Record<string, unknown>) => {
    console.log('Form validation errors:', errors);
    
    // Display specific validation errors
    const errorMessages: string[] = [];
    if (errors.guide_name) {
      const error = errors.guide_name as { message?: string } | undefined;
      errorMessages.push(`Guide Name: ${error?.message || 'Required'}`);
    }
    if (errors.customer_id) {
      const error = errors.customer_id as { message?: string } | undefined;
      errorMessages.push(`Customer ID: ${error?.message || 'Required'}`);
    }
    // Check option IDs that might be invalid UUIDs
    Object.keys(errors).forEach((key) => {
      if (key.includes('option_item_id') && errors[key]) {
        const error = errors[key] as { message?: string } | undefined;
        errorMessages.push(`${key}: ${error?.message || 'Invalid value'}`);
      }
    });
    
    if (errorMessages.length > 0) {
      toast.error(`Validation errors: ${errorMessages.join(', ')}`);
    } else {
      toast.error('Please fix the form errors before submitting');
    }
  };

  const handleDiscard = async () => {
    const actualStyleGuideId = styleGuideId || guide?.style_guide_id;
    
    if (!actualStyleGuideId) {
      // If no style guide exists, just reset the form
      reset(defaultValues);
      setShowDiscardModal(false);
      return;
    }

    try {
      // Reload the style guide from the database
      console.log('Reloading style guide from database:', actualStyleGuideId);
      const supabase = createClient();
      
      const { data: freshGuide, error } = await supabase
        .from('style_guides')
        .select(`
          *,
          formality_option_item:formality_option_items(*),
          sentence_length_option_item:sentence_option_items_singleton(*),
          pacing_option_item:pacing_option_items(*),
          humor_usage_option_item:humor_usage_option_items(*),
          storytelling_style_option_item:storytelling_option_items(*),
          use_of_jargon_option_item:use_of_jargon_option_items(*),
          language_level_option_item:language_level_option_items(*)
        `)
        .eq('style_guide_id', actualStyleGuideId)
        .single();

      if (error) {
        console.error('Error reloading style guide:', error);
        toast.error('Failed to reload style guide from database');
        setShowDiscardModal(false);
        return;
      }

      // Reset form with fresh data from database
      reset({
        customer_id: freshGuide.customer_id,
        guide_name: freshGuide.guide_name,
        brand_personality: freshGuide.brand_personality || '',
        brand_voice: freshGuide.brand_voice || '',
        formality_option_item_id: freshGuide.formality_option_item_id || null,
        sentence_length_option_item_id: freshGuide.sentence_length_option_item_id || null,
        pacing_option_item_id: freshGuide.pacing_option_item_id || null,
        humor_usage_option_item_id: freshGuide.humor_usage_option_item_id || null,
        storytelling_style_option_item_id: freshGuide.storytelling_style_option_item_id || null,
        use_of_jargon_option_item_id: freshGuide.use_of_jargon_option_item_id || null,
        language_level_option_item_id: freshGuide.language_level_option_item_id || null,
        inclusivity_guidelines: freshGuide.inclusivity_guidelines || '',
        active: freshGuide.active ?? true,
      });

      toast.success('Changes discarded - form reloaded from database');
      setShowDiscardModal(false);
    } catch (err) {
      console.error('Exception reloading style guide:', err);
      toast.error('An unexpected error occurred');
      setShowDiscardModal(false);
    }
  };

  const isLoading = createMutation.isPending || updateMutation.isPending;

  return (
    <Box>
      <form onSubmit={handleSubmit(onSubmit, onError)}>
        <Stack spacing={4}>
          {/* Form Header with Actions */}
          <Stack 
            direction="row" 
            justifyContent="space-between" 
            alignItems="center"
            flexWrap="wrap"
            gap={2}
          >
            <Stack direction="row" spacing={2}>
              {(styleGuideId || guide?.style_guide_id) && (
                <Button
                  type="button"
                  variant="outlined"
                  startDecorator={<MagicWand />}
                  onClick={handleReanalyzeSite}
                  disabled={isLoading || isReanalyzing}
                  loading={isReanalyzing}
                >
                  Reanalyze Site
                </Button>
              )}
            </Stack>
            <Stack direction="row" spacing={2}>
              <Button
                type="button"
                variant="outlined"
                color="neutral"
                onClick={() => setShowDiscardModal(true)}
                disabled={!isDirty || isLoading || isReanalyzing}
              >
                Discard Changes
              </Button>
              <Button
                type="submit"
                loading={isLoading}
                disabled={isReanalyzing}
                startDecorator={<FloppyDisk />}
              >
                Save Style Guide
              </Button>
            </Stack>
          </Stack>

          {/* Single Column Layout */}
          <Stack spacing={3}>
            {/* Guide Name - Only show when there's a validation error */}
            {errors.guide_name && (
              <FormControl error={!!errors.guide_name}>
                <FormLabel>Guide Name *</FormLabel>
                <Input
                  {...register('guide_name')}
                  placeholder="Enter guide name"
                  slotProps={{
                    input: {
                      maxLength: 120,
                    },
                  }}
                  aria-label="Guide name"
                  aria-describedby="guide-name-error"
                  aria-required="true"
                />
                <FormHelperText id="guide-name-error">
                  {(errors.guide_name as { message?: string })?.message}
                </FormHelperText>
                <FormHelperText>{watch('guide_name')?.length || 0}/120 characters</FormHelperText>
              </FormControl>
            )}
            
            {/* Hidden input to maintain form registration for validation */}
            <Box component="input" type="hidden" {...register('guide_name')} />

            {/* Brand Personality */}
            <FormControl error={!!errors.brand_personality}>
              <FormLabel>Brand Personality</FormLabel>
              <Textarea
                {...register('brand_personality')}
                placeholder="3-6 sentence summary of brand personality attributes"
                minRows={4}
                aria-label="Brand personality"
                aria-describedby="brand-personality-helper"
              />
              <FormHelperText id="brand-personality-helper">
                Provide a concise summary of your brand&apos;s personality traits
              </FormHelperText>
            </FormControl>

            {/* Brand Voice Attributes */}
            <FormControl error={!!errors.brand_voice}>
              <FormLabel>Brand Voice Attributes</FormLabel>
              <Input
                {...register('brand_voice')}
                placeholder="Enter brand voice attributes (e.g., Trustworthy, Conversational, Confident)"
                aria-label="Brand voice attributes"
                aria-describedby={errors.brand_voice ? 'brand-voice-error' : 'brand-voice-helper'}
              />
              {errors.brand_voice && (
                <FormHelperText id="brand-voice-error">
                  {(errors.brand_voice as { message?: string })?.message}
                </FormHelperText>
              )}
              <FormHelperText id="brand-voice-helper">
                Common examples: Trustworthy, Conversational, Confident, Professional, Friendly
              </FormHelperText>
            </FormControl>

            {/* Formality */}
            <FormControl>
              <FormLabel>Formality Level</FormLabel>
              <Select
                value={watch('formality_option_item_id') || ''}
                onChange={(_event, value) => setValue('formality_option_item_id', value || null)}
                placeholder="Select formality level"
                aria-label="Formality level"
              >
                {formalityOptions.map((option) => (
                  <Option key={option.formality_option_item_id} value={option.formality_option_item_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('formality_option_item_id') && (
                <FormHelperText>
                  {formalityOptions.find(o => o.formality_option_item_id === watch('formality_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Sentence Length */}
            <FormControl>
              <FormLabel>Sentence Length Preference</FormLabel>
              <Select
                value={watch('sentence_length_option_item_id') || ''}
                onChange={(event, value) => {
                  const newValue = value === null ? null : (typeof value === 'string' ? value : null);
                  setValue('sentence_length_option_item_id', newValue, { shouldValidate: true });
                }}
                placeholder={isLoadingSentenceOptions ? "Loading options..." : "Select sentence length"}
                aria-label="Sentence length preference"
                disabled={isLoadingSentenceOptions}
              >
                {sentenceOptions.map((option) => (
                  <Option key={option.sentence_option_items_id} value={option.sentence_option_items_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('sentence_length_option_item_id') && (
                <FormHelperText>
                  {sentenceOptions.find(o => o.sentence_option_items_id === watch('sentence_length_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Pacing */}
            <FormControl>
              <FormLabel>Pacing Preference</FormLabel>
              <Select
                value={watch('pacing_option_item_id') || ''}
                onChange={(_event, value) => setValue('pacing_option_item_id', value || null)}
                placeholder="Select pacing"
                aria-label="Pacing preference"
              >
                {pacingOptions.map((option) => (
                  <Option key={option.pacing_option_item_id} value={option.pacing_option_item_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('pacing_option_item_id') && (
                <FormHelperText>
                  {pacingOptions.find(o => o.pacing_option_item_id === watch('pacing_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Humor Usage */}
            <FormControl>
              <FormLabel>Humor Usage</FormLabel>
              <Select
                value={watch('humor_usage_option_item_id') || ''}
                onChange={(_event, value) => setValue('humor_usage_option_item_id', value || null)}
                placeholder="Select humor usage"
                aria-label="Humor usage"
              >
                {humorOptions.map((option) => (
                  <Option key={option.humor_usage_option_item_id} value={option.humor_usage_option_item_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('humor_usage_option_item_id') && (
                <FormHelperText>
                  {humorOptions.find(o => o.humor_usage_option_item_id === watch('humor_usage_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Storytelling Style */}
            <FormControl>
              <FormLabel>Storytelling Style</FormLabel>
              <Select
                value={watch('storytelling_style_option_item_id') || ''}
                onChange={(_event, value) => setValue('storytelling_style_option_item_id', value || null)}
                placeholder="Select storytelling style"
                aria-label="Storytelling style"
              >
                {storytellingOptions.map((option) => (
                  <Option key={option.storytelling_option_item_id} value={option.storytelling_option_item_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('storytelling_style_option_item_id') && (
                <FormHelperText>
                  {storytellingOptions.find(o => o.storytelling_option_item_id === watch('storytelling_style_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Use of Jargon */}
            <FormControl>
              <FormLabel>Use of Jargon</FormLabel>
              <Select
                value={watch('use_of_jargon_option_item_id') || ''}
                onChange={(_event, value) => setValue('use_of_jargon_option_item_id', value || null)}
                placeholder="Select jargon usage"
                aria-label="Use of jargon"
              >
                {jargonOptions.map((option) => (
                  <Option key={option.use_of_jargon_option_item_id} value={option.use_of_jargon_option_item_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('use_of_jargon_option_item_id') && (
                <FormHelperText>
                  {jargonOptions.find(o => o.use_of_jargon_option_item_id === watch('use_of_jargon_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Language Level */}
            <FormControl>
              <FormLabel>Language Level</FormLabel>
              <Select
                value={watch('language_level_option_item_id') || ''}
                onChange={(_event, value) => setValue('language_level_option_item_id', value || null)}
                placeholder="Select language level"
                aria-label="Language level"
              >
                {languageOptions.map((option) => (
                  <Option key={option.language_level_option_item_id} value={option.language_level_option_item_id}>
                    {option.display_name}
                  </Option>
                ))}
              </Select>
              {watch('language_level_option_item_id') && (
                <FormHelperText>
                  {languageOptions.find(o => o.language_level_option_item_id === watch('language_level_option_item_id'))?.description || 'No description available'}
                </FormHelperText>
              )}
            </FormControl>

            {/* Inclusivity Guidelines */}
            <FormControl error={!!errors.inclusivity_guidelines}>
              <FormLabel>Inclusivity Guidelines</FormLabel>
              <Textarea
                {...register('inclusivity_guidelines')}
                placeholder="Machine-readable summary of inclusivity constraints and principal rules"
                minRows={6}
                aria-label="Inclusivity guidelines"
                aria-describedby="inclusivity-helper"
              />
              <FormHelperText id="inclusivity-helper">
                Define inclusivity rules and constraints for content generation
              </FormHelperText>
            </FormControl>
          </Stack>
        </Stack>
      </form>

      {/* Discard Changes Modal */}
      <Modal open={showDiscardModal} onClose={() => setShowDiscardModal(false)}>
        <ModalDialog
          role="dialog"
          aria-modal="true"
          aria-labelledby="discard-modal-title"
        >
          <ModalClose />
          <Typography id="discard-modal-title" level="h2">
            Discard Changes?
          </Typography>
          <Typography sx={{ mt: 2 }}>
            Are you sure you want to discard all unsaved changes?
          </Typography>
          <Stack direction="row" spacing={2} sx={{ mt: 3 }}>
            <Button
              variant="outlined"
              onClick={() => setShowDiscardModal(false)}
              onKeyDown={(e) => {
                if (e.key === 'Escape') {
                  setShowDiscardModal(false);
                }
              }}
            >
              Cancel
            </Button>
            <Button
              color="danger"
              onClick={handleDiscard}
            >
              Discard Changes
            </Button>
          </Stack>
        </ModalDialog>
      </Modal>

      {/* Reanalyze Site Modal */}
      <Modal open={showReanalyzeModal} onClose={() => !isReanalyzing && setShowReanalyzeModal(false)}>
        <ModalDialog
          role="dialog"
          aria-modal="true"
          aria-labelledby="reanalyze-modal-title"
        >
          <ModalClose disabled={isReanalyzing} />
          <Typography id="reanalyze-modal-title" level="h2">
            Reanalyze Website?
          </Typography>
          <Typography sx={{ mt: 2 }}>
            This will delete the current style guide and regenerate it by analyzing your website.
            Any manual edits will be lost. This process may take 30-60 seconds.
          </Typography>
          
          <FormControl sx={{ mt: 2 }}>
            <FormLabel>Website URL</FormLabel>
            <Input
              value={websiteUrl}
              onChange={(e) => setWebsiteUrl(e.target.value)}
              placeholder="https://www.example.com"
              type="url"
              disabled={isReanalyzing}
            />
            <FormHelperText>
              The website that will be analyzed for style guide generation
            </FormHelperText>
          </FormControl>

          <Stack direction="row" spacing={2} sx={{ mt: 3 }}>
            <Button
              variant="outlined"
              onClick={() => setShowReanalyzeModal(false)}
              disabled={isReanalyzing}
            >
              Cancel
            </Button>
            <Button
              color="danger"
              onClick={handleConfirmReanalyze}
              loading={isReanalyzing}
              disabled={!websiteUrl || isReanalyzing}
              startDecorator={!isReanalyzing && <MagicWand />}
            >
              {isReanalyzing ? 'Analyzing...' : 'Reanalyze & Regenerate'}
            </Button>
          </Stack>
        </ModalDialog>
      </Modal>
    </Box>
  );
}

