import type { AppData } from './testData.types';

export const appData: AppData = {
  accessDeniedMessage: 'Access Denied',
  authorization: {
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    confirmEmailModal: 'Confirm your email',
    profileUpdateAlert: 'Password and profile updated successfully. Please sign in again.',
    setNewPasswordModal: 'Set new password',
  },
  pages: {
    userManagement: 'User Management',
    documentation: 'Documentation',
    roleSettings: 'Role Settings',
    customerManagement: 'Customer Management',
    systemUsers: 'System Users Management',
  },
  userManagementTable: {
    userName: 'User name',
    email: 'Email',
    customer: 'Customer',
    role: 'Role',
  },
  customerManagementTable: {
    customer: 'Customer',
    manager: 'Manager',
    users: 'Users',
    subscription: 'Subscription',
  },
  userStatuses: {
    active: 'Active',
    inactive: 'Inactive',
  },
  userMenuButtons: {
    profile: 'Profile',
    settings: 'Settings',
    signOut: 'Sign Out',
  },
  emailSubject: {
    completeRegistration: 'Confirm Your Signup',
    invitation: 'You have been invited',
  },
  messages: {
    emptyTable: 'No items found',
  },
  registrationErrors: {
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    emailRequired: 'Email is required',
    passwordRequired: 'Password must be at least 8 characters long',
    termsAndConditionsError: 'You must accept the terms and conditions',
    firstAndLastNameLength:
      'Password should be at least 8 characters. Password should contain at least one character of each: abcdefghijklmnopqrstuvwxyz, ABCDEFGHIJKLMNOPQRSTUVWXYZ, 0123456789, !@#$%^&*()_+-=[]{};\':"|<>?,./`~.',
    existsMail: 'User with this email already exists',
    invalidPassword: 'Password must contain at least one number',
    invalidMail:
      'Please use your work email instead of a personal one (@gmail, @yahoo, etc.) to connect with your company. Personal email domains cannot join existing companies.',
  },
  addRolePageData: {
    addRoleModal: 'Add Role',
    peopleCount: ' people',
    addRole: {
      roleName: 'Enter role name',
      about: "Describe this role's permissions and responsibilities",
      permissionSwitchers: 'Enable or disable this permission group for the role',
      userManagementToggle: 'User Management',
      documentsToggle: 'Documents',
      createRoleButton: 'Create Role',
      cancelCreateRoleButton: 'Cancel',
    },
    userManagementPermission: {
      view: 'View Users',
      create: 'Create User',
      invite: 'Invite User',
      edit: 'Edit User',
    },
    documentsPermission: {
      viewCategories: 'View Categories',
      createCategories: 'Create Categories',
      editCategories: 'Edit Categories',
      deleteCategories: 'Delete Categories',
      viewArticles: 'View Articles',
      createArticles: 'Create Articles',
      editArticles: 'Edit Articles',
      deleteArticles: 'Delete Articles',
    },
  },
  actions: {
    openDetail: 'Open detail',
    edit: 'Edit',
    delete: 'Delete',
  },
  userManagementPageData: {
    editUserModal: 'Edit user',
    impersonateUserButton: 'Impersonate user',
    saveButton: 'Save',
    userUpdatedAlert: 'User updated successfully.',
    usersCreatedAlert: 'User created successfully.',
    userInvitedAlert: 'User andrii.petrenko+jvfvnlk@huboxt.com has been successfully invited',
    usersInvitedAlert: 'Users have been successfully invited:',
    addUser: 'Add user',
    addUsers: 'Add users',
    invite: 'Invite',
    editUserData: {
      firstName: 'Enter first name',
      lastName: 'Enter last name',
      email: 'Enter email',
      customer: 'Customer',
      role: 'Role',
    },
  },
  documentationPageData: {
    addCategoryButton: 'Add category',
    addArticleButton: 'Add article',
    categoryCreatedAlert: 'Category created successfully.',
    articles: ' articles',
    categoryModal: {
      modalName: 'Add category',
      categoryNameInput: 'Enter category name',
      subcategoryDropdown: 'Subcategory',
      aboutInput: 'Enter description',
      addIconDropdown: 'Add icon',
      addNewCategory: 'Add new category',
      newSubcategoryInput: 'Enter new subcategory',
      addIcons: {
        star: 'Star',
        rocketLaunch: 'RocketLaunch',
        api: 'Api',
        code: 'Code',
        settings: 'Settings',
        fix: 'Fix',
        badge: 'Badge',
      },
    },
    deleteCategoryModal: {
      modalName: 'Delete Category',
      confirmDeleteButton: 'Delete permanently',
      categoryDeletedAlert: 'Category has been deleted successfully!',
    },
  },
  articlesPageData: {
    noArticlesMessage: 'You do not have any articles',
    addArticlesMessage: 'Add articles avialable for this category.',
    addArticleButton: 'Add article',
    saveAsDraft: 'Save as a draft',
    publish: 'Publish',
    articleCreatedAlert: 'Article has been created successfully!',
    articleUpdatedAlert: 'Article has been updated successfully!',
    loadingText: 'Loading...',
    deleteArticleModal: {
      modalName: 'Delete article',
      articleDeleteButton: 'Delete permanently',
      articleDeletedAlert: 'Articles have been deleted successfully!',
    },
  },
  addArticleModal: {
    articleTitlePlaceholder: 'Enter article title',
    categoryDropdown: 'Category',
    subcategoryDropdown: 'Subcategory',
    pasteLinkPlaceholder: 'Paste link',
  },
  articleTableData: {
    articleName: 'Article name',
    lastEdit: 'Last edit',
    status: 'Status',
    author: 'Author',
    performance: 'Performance',
  },
  statuses: {
    draft: 'Draft',
    published: 'Published',
  },
  addRoleErrors: {
    roleNameRequired: 'Role name is required',
    descriptionRequired: 'Description is required',
    permissionRequired: 'At least one module must have permissions enabled and selected',
    selectedPermissionRequired: 'Modules with enabled permissions must have at least one permission selected',
    roleNameLength: 'Role name must be shorter than or equal to 96 characters',
  },
};
