/**
 * Response Processors - Public API
 *
 * Entry point for the response processor framework.
 * getResponseProcessor is loaded from registry.ts when present (generated by pnpm supabase:wrap-functions);
 * otherwise falls back to returning null (platform repo without generated artifacts).
 */
import type { ResponseProcessor } from './types.ts';
export type { ResponseProcessor } from './types.ts';
export { cleanJsonResponse } from './utils.ts';

const registry = await import('./registry.ts').catch(() => ({
  getResponseProcessor: (_: string | null | undefined): ResponseProcessor | null => null,
}));

export const getResponseProcessor = registry.getResponseProcessor;
